# Generated by Django 5.0.9 on 2026-08-26 20:56

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف (ناعم)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('official_letters', 'كتب رسمية'), ('correspondence', 'مخاطبات'), ('statements', 'بيانات'), ('decisions', 'قرارات'), ('reports', 'تقارير'), ('activities', 'نشاطات'), ('other', 'وثائق أخرى')], max_length=30, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('keywords', models.CharField(blank=True, help_text='افصل بينها بفواصل، تُستخدم في البحث.', max_length=300, verbose_name='الكلمات المفتاحية')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\ALMWOSHOOR\\Desktop\\naib-office-system\\protected_media'), upload_to='archive/%Y/%m/', verbose_name='الملف')),
                ('visibility', models.CharField(choices=[('public', 'عام (يظهر للمواطنين)'), ('internal', 'داخلي (للموظفين فقط)')], default='internal', max_length=20, verbose_name='مستوى الظهور')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'وثيقة أرشيف',
                'verbose_name_plural': 'وثائق الأرشيف',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['category', 'year'], name='archive_arc_categor_3c6b70_idx')],
            },
        ),
    ]
