# Generated by Django 5.0.9 on 2026-08-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم اللجنة/الاختصاص')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'لجنة/اختصاص',
                'verbose_name_plural': 'اللجان والاختصاصات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeputyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('title', models.CharField(blank=True, help_text='مثال: عضو مجلس النواب العراقي', max_length=200, verbose_name='اللقب/المنصب')),
                ('photo', models.ImageField(blank=True, help_text='يُستبدل بها Placeholder الافتراضي بمجرد رفعها.', null=True, upload_to='deputy/', verbose_name='الصورة الرسمية')),
                ('biography', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
                ('professional_background', models.TextField(blank=True, verbose_name='السيرة المهنية والعلمية')),
                ('parliamentary_activity', models.TextField(blank=True, verbose_name='النشاط النيابي')),
            ],
            options={
                'verbose_name': 'بروفايل النائب',
                'verbose_name_plural': 'بروفايل النائب (سجل واحد فقط)',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='الرابط المختصر')),
                ('item_type', models.CharField(choices=[('news', 'خبر'), ('statement', 'بيان'), ('visit', 'زيارة'), ('meeting', 'لقاء'), ('field_activity', 'نشاط ميداني'), ('session', 'جلسة')], default='news', max_length=20, verbose_name='النوع')),
                ('summary', models.CharField(blank=True, max_length=400, verbose_name='ملخص قصير')),
                ('body', models.TextField(verbose_name='المحتوى الكامل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='الصورة الرئيسية')),
                ('video_url', models.URLField(blank=True, help_text='رابط يوتيوب أو أي منصة أخرى، يُعرض كرابط مضمّن.', verbose_name='رابط فيديو (اختياري)')),
                ('published_at', models.DateTimeField(verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'خبر/نشاط',
                'verbose_name_plural': 'الأخبار والنشاطات',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('sub_district', models.CharField(blank=True, max_length=100, verbose_name='الناحية')),
            ],
            options={
                'verbose_name': 'مواطن',
                'verbose_name_plural': 'المواطنون',
                'indexes': [models.Index(fields=['phone'], name='citizens_ci_phone_b586dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='citizens.newsitem')),
            ],
            options={
                'verbose_name': 'صورة معرض',
                'verbose_name_plural': 'صور المعرض',
                'ordering': ['order', 'id'],
            },
        ),
    ]
