# Generated by Django 5.0.9 on 2026-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم النائب')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='الاختصاص')),
                ('committee', models.CharField(blank=True, max_length=200, verbose_name='اللجنة')),
                ('official_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الرسمي')),
                ('office_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المكتب')),
                ('secretary_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد السكرتير')),
                ('email_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('bouncing', 'يرتد (Bouncing)')], default='active', max_length=20, verbose_name='حالة البريد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نائب نشط')),
            ],
            options={
                'verbose_name': 'نائب آخر',
                'verbose_name_plural': 'النواب الآخرون',
                'ordering': ['full_name'],
                'permissions': [('can_manage_deputy_emails', 'يمكنه إضافة/تعديل بريد النائب')],
            },
        ),
    ]
