# Generated by Django 5.0.9 on 2026-08-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deputies', '0001_initial'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('replied', 'وصل الرد'), ('followed_up', 'تمت المتابعة'), ('done', 'تم الإنجاز')], default='sent', max_length=20, verbose_name='حالة التحويل')),
                ('reply_received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ وصول الرد')),
                ('reply_summary', models.TextField(blank=True, verbose_name='ملخص الرد')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_assignments', to='deputies.deputy')),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المحيل')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requests_app.citizenrequest')),
            ],
            options={
                'verbose_name': 'تحويل طلب',
                'verbose_name_plural': 'تحويلات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('sent', 'نجح'), ('failed', 'فشل')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='requests_app.citizenrequest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='communications.requestassignment')),
            ],
            options={
                'verbose_name': 'سجل بريد',
                'verbose_name_plural': 'سجلات البريد',
                'ordering': ['-created_at'],
            },
        ),
    ]
