# Generated by Django 5.0.9 on 2026-08-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('complaint_category', models.CharField(blank=True, max_length=150, verbose_name='تصنيف الشكوى')),
                ('complaint_location', models.CharField(blank=True, max_length=250, verbose_name='موقع الشكوى')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_detail', to='requests_app.citizenrequest')),
            ],
            options={
                'verbose_name': 'تفاصيل شكوى',
                'verbose_name_plural': 'تفاصيل الشكاوى',
            },
        ),
    ]
