# Generated by Django 5.0.9 on 2026-08-26 20:56

import apps.requests_app.validators
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف (ناعم)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True, verbose_name='رقم التتبع')),
                ('request_type', models.CharField(choices=[('complaint', 'شكوى'), ('request', 'طلب'), ('inquiry', 'استعلام')], max_length=20, verbose_name='نوع الطلب')),
                ('subject', models.CharField(max_length=250, verbose_name='عنوان الطلب')),
                ('details', models.TextField(verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('needs_info', 'بحاجة إلى معلومات'), ('forwarded', 'تمت الإحالة'), ('awaiting_reply', 'بانتظار الرد'), ('in_progress', 'قيد المتابعة'), ('completed', 'مكتمل'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('sub_district', models.CharField(blank=True, max_length=100, verbose_name='الناحية')),
                ('privacy_consent', models.BooleanField(default=False, verbose_name='الموافقة على سياسة الخصوصية')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='citizens.citizen', verbose_name='المواطن')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'permissions': [('view_all_requests', 'يمكنه مشاهدة كل الطلبات (وليس المسندة له فقط)'), ('can_forward_request', 'يمكنه تحويل الطلب لنائب آخر')],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='C:\\Users\\ALMWOSHOOR\\Desktop\\naib-office-system\\protected_media'), upload_to='request_attachments/%Y/%m/', validators=[apps.requests_app.validators.validate_attachment], verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.citizenrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفعه (فارغ = المواطن نفسه)')),
            ],
            options={
                'verbose_name': 'مرفق طلب',
                'verbose_name_plural': 'مرفقات الطلبات',
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('old_status', models.CharField(blank=True, choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('needs_info', 'بحاجة إلى معلومات'), ('forwarded', 'تمت الإحالة'), ('awaiting_reply', 'بانتظار الرد'), ('in_progress', 'قيد المتابعة'), ('completed', 'مكتمل'), ('closed', 'مغلق')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('needs_info', 'بحاجة إلى معلومات'), ('forwarded', 'تمت الإحالة'), ('awaiting_reply', 'بانتظار الرد'), ('in_progress', 'قيد المتابعة'), ('completed', 'مكتمل'), ('closed', 'مغلق')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.citizenrequest')),
            ],
            options={
                'verbose_name': 'سجل تغيير حالة',
                'verbose_name_plural': 'سجلات تغيير الحالة',
                'ordering': ['created_at'],
            },
        ),
    ]
