# Generated by Django 5.0.9 on 2026-08-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('appointment_type', models.CharField(choices=[('general_meeting', 'لقاء عام مع النائب'), ('complaint_followup', 'متابعة شكوى/طلب'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الموعد')),
                ('requested_date', models.DateField(verbose_name='التاريخ')),
                ('requested_time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكَّد'), ('rescheduled', 'أُعيدت جدولته'), ('cancelled', 'مُلغى'), ('completed', 'منتهٍ')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='citizens.citizen', verbose_name='المواطن')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أكّده')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['requested_date', 'requested_time'],
            },
        ),
    ]
